export const LAND_TYPE = [
  { code: "NNP", name: "Nhóm đất nông nghiệp", frequency: 0 },
  { code: "CHN", name: "Đất trồng cây hằng năm", frequency: 0 },
  { code: "LUA", name: "Đất trồng lúa", frequency: 1 },
  { code: "LUC", name: "Đất chuyên trồng lúa", frequency: 2 },
  { code: "LUK", name: "Đất trồng lúa còn lại", frequency: 0 },
  { code: "HNK", name: "Đất trồng cây hằng năm khác", frequency: 0 },
  { code: "CLN", name: "Đất trồng cây lâu năm", frequency: 3 },
  { code: "LNP", name: "Đất lâm nghiệp", frequency: 0 },
  { code: "RDD", name: "Đất rừng đặc dụng", frequency: 0 },
  { code: "RPH", name: "Đất rừng phòng hộ", frequency: 0 },
  { code: "RSX", name: "Đất rừng sản xuất", frequency: 0 },
  { code: "RSN", name: "Đất rừng sản xuất là rừng tự nhiên", frequency: 0 },
  { code: "NTS", name: "Đất nuôi trồng thủy sản", frequency: 1 },
  { code: "CNT", name: "Đất chăn nuôi tập trung", frequency: 0 },
  { code: "LMU", name: "Đất làm muối", frequency: 0 },
  { code: "NKH", name: "Đất nông nghiệp khác", frequency: 0 },
  { code: "PNN", name: "Nhóm đất phi nông nghiệp", frequency: 0 },
  { code: "OTC", name: "Đất ở", frequency: 0 },
  { code: "ONT", name: "Đất ở tại nông thôn", frequency: 4 },
  { code: "ODT", name: "Đất ở tại đô thị", frequency: 5 },
  { code: "TSC", name: "Đất xây dựng trụ sở cơ quan", frequency: 0 },
  { code: "CQA", name: "Đất quốc phòng, an ninh", frequency: 0 },
  { code: "CQP", name: "Đất quốc phòng", frequency: 0 },
  { code: "CAN", name: "Đất an ninh", frequency: 0 },
  { code: "DSN", name: "Đất xây dựng công trình sự nghiệp", frequency: 0 },
  { code: "DVH", name: "Đất xây dựng cơ sở văn hóa", frequency: 0 },
  { code: "DXH", name: "Đất xây dựng cơ sở xã hội", frequency: 0 },
  { code: "DYT", name: "Đất xây dựng cơ sở y tế", frequency: 0 },
  { code: "DGD", name: "Đất xây dựng cơ sở giáo dục và đào tạo", frequency: 0 },
  { code: "DTT", name: "Đất xây dựng cơ sở thể dục, thể thao", frequency: 0 },
  { code: "DKH", name: "Đất xây dựng cơ sở khoa học và công nghệ", frequency: 0 },
  { code: "DMT", name: "Đất xây dựng cơ sở môi trường", frequency: 0 },
  { code: "DKT", name: "Đất xây dựng cơ sở khí tượng thủy văn", frequency: 0 },
  { code: "DNG", name: "Đất xây dựng cơ sở ngoại giao", frequency: 0 },
  { code: "DSK", name: "Đất xây dựng công trình sự nghiệp khác", frequency: 0 },
  { code: "CSK", name: "Đất sản xuất, kinh doanh phi nông nghiệp", frequency: 0 },
  { code: "SCC", name: "Đất khu công nghiệp, cụm công nghiệp", frequency: 0 },
  { code: "SKK", name: "Đất khu công nghiệp", frequency: 0 },
  { code: "SKN", name: "Đất cụm công nghiệp", frequency: 0 },
  { code: "SCT", name: "Đất khu công nghệ thông tin tập trung", frequency: 0 },
  { code: "TMD", name: "Đất thương mại, dịch vụ", frequency: 0 },
  { code: "SKC", name: "Đất cơ sở sản xuất phi nông nghiệp", frequency: 0 },
  { code: "SKS", name: "Đất sử dụng cho hoạt động khoáng sản", frequency: 0 },
  { code: "CCC", name: "Đất sử dụng vào mục đích công cộng", frequency: 0 },
  { code: "DGT", name: "Đất công trình giao thông", frequency: 0 },
  { code: "DTL", name: "Đất công trình thủy lợi", frequency: 0 },
  { code: "DCT", name: "Đất công trình cấp nước, thoát nước", frequency: 0 },
  { code: "DPC", name: "Đất công trình phòng, chống thiên tai", frequency: 0 },
  { code: "DDD", name: "Đất có di tích lịch sử - văn hóa, danh thắng", frequency: 0 },
  { code: "DRA", name: "Đất công trình xử lý chất thải", frequency: 0 },
  { code: "DNL", name: "Đất công trình năng lượng, chiếu sáng công cộng", frequency: 0 },
  { code: "DBV", name: "Đất công trình hạ tầng bưu chính, viễn thông, CNTT", frequency: 0 },
  { code: "DCH", name: "Đất chợ dân sinh, chợ đầu mối", frequency: 0 },
  { code: "DKV", name: "Đất khu vui chơi, sinh hoạt cộng đồng", frequency: 0 },
  { code: "TON", name: "Đất tôn giáo", frequency: 0 },
  { code: "TIN", name: "Đất tín ngưỡng", frequency: 0 },
  { code: "NTD", name: "Đất nghĩa trang, hỏa táng, lưu trữ tro cốt", frequency: 0 },
  { code: "TVC", name: "Đất có mặt nước chuyên dùng", frequency: 0 },
  { code: "MNC", name: "Đất có mặt nước dạng ao, hồ, đầm, phá", frequency: 0 },
  { code: "SON", name: "Đất có mặt nước dạng sông, kênh, rạch, suối", frequency: 0 },
  { code: "PNK", name: "Đất phi nông nghiệp khác", frequency: 0 },
  { code: "CSD", name: "Nhóm đất chưa sử dụng", frequency: 0 },
  { code: "CGT", name: "Đất thu hồi chưa giao, chưa cho thuê", frequency: 0 },
  { code: "BCS", name: "Đất bằng chưa sử dụng", frequency: 0 },
  { code: "DCS", name: "Đất đồi núi chưa sử dụng", frequency: 0 },
  { code: "NCS", name: "Núi đá không có rừng cây", frequency: 0 },
  { code: "MCS", name: "Đất có mặt nước chưa sử dụng", frequency: 0 }
];